version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  celery-worker:
    build: .
    container_name: celery-worker
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/app
    command: celery -A src.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis

  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis
      - celery-worker

